"""Added snippets schema

Revision ID: 2e3f3b8566f5
Revises: 
Create Date: 2022-05-23 07:23:23.732809

"""
import sqlmodel
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2e3f3b8566f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('creator_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('creator_origin', 'creator_username', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snippet')
    # ### end Alembic commands ###
