"""Added programming language info to snippet table

Revision ID: be2fa1db0613
Revises: e1cb123acff2
Create Date: 2022-05-31 12:49:27.455668

"""
import sqlmodel
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'be2fa1db0613'
down_revision = 'e1cb123acff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('snippet', sa.Column('language_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('snippet', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snippet', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('snippet', 'language_version')
    op.drop_column('snippet', 'language')
    # ### end Alembic commands ###
