"""Set to code text type

Revision ID: cbbec12b6de5
Revises: be2fa1db0613
Create Date: 2022-05-31 13:00:12.098320

"""
import sqlmodel
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cbbec12b6de5'
down_revision = 'be2fa1db0613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snippet', 'code', type_=sa.Text())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snippet', 'code', type_=sa.String())
    # ### end Alembic commands ###
