"""Added snippets schema

Revision ID: e1cb123acff2
Revises: 
Create Date: 2022-05-24 16:27:20.408347

"""
import sqlmodel
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e1cb123acff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('creator_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('creator_username', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snippet')
    # ### end Alembic commands ###
